"""
Django settings for jam project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from .base import *


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mbv-$a^z@1-*5_7hm+4&yeu(5%*33pszwxkd-y*9ergq2o4t@z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
DEVELOPMENT, PRODUCTION = True, False
DEBUG_TOOLBAR = True

INSTALLED_APPS += [
    'apps.dev',
    'django_extensions',
]

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '..', 'client', "static"),
    os.path.join(BASE_DIR, '..', 'apps', 'front_end', 'static'),  # I think this should work? Lemme know if it doesn't
]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
